---
# create_krb5_conf/tasks/main.yml

- name: 'Create /etc/krb5.conf from template'
  ansible.builtin.template:
    src: 'krb5.conf.j2'
    dest: '/etc/krb5.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
